---
# tasks file for MYSQL
- name: Install MySQL on the master instance
  include_tasks: mysql_master.yml
  when: "inventory_hostname in groups['tag_Name_MySQL']"

- name: Install MySQL on the slave instance
  include_tasks: mysql_slave.yml
  when: "inventory_hostname in groups['tag_Name_MySQL_replica']"

- name: Install HAProxy on the public instance
  include_tasks: Public_EC2.yml
  when: "inventory_hostname in groups['tag_Name_Public_EC2']"
