---
- name: Copy the Private key
  copy:
    src: /var/lib/jenkins/Kaustubh.pem
    dest: /home/ubuntu/Kaustubh.pem
   
- name: Install HAProxy
  apt:
    name: haproxy
    state: present

- name: Copy HAProxy configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: Start HAProxy service
  service:
    name: haproxy
    state: started
    enabled: true
